version: 2
updates:
  - package-ecosystem: gradle
    directory: /intellij
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /vscode
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /visual-studio/SecretLoader
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
